// flow-typed signature: 423cecefa5b76f98764fad79d33401dd
// flow-typed version: <<STUB>>/babel-plugin-transform-custom-element-classes_v^0.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-custom-element-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-custom-element-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-custom-element-classes/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-custom-element-classes/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-custom-element-classes/lib/index'>;
}
