// flow-typed signature: f6559acc86f975ef0bf9b7b784a2c390
// flow-typed version: <<STUB>>/buble-loader_v^0.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buble-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buble-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'buble-loader/index' {
  declare module.exports: $Exports<'buble-loader'>;
}
declare module 'buble-loader/index.js' {
  declare module.exports: $Exports<'buble-loader'>;
}
