// flow-typed signature: 81de65ad9de53a0a72e18f6dcc942266
// flow-typed version: <<STUB>>/cycle-onionify_v4.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cycle-onionify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cycle-onionify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cycle-onionify/examples/advanced/dist/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/advanced/lib/Item' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/advanced/lib/List' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/advanced/lib/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/advanced/lib/TodoApp' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/basic/dist/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/basic/src/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/dist/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/lib/Edit' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/lib/Item' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/lib/List' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/lib/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/lenses/lib/RadioApp' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/dist/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/lib/Counter' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/lib/Item' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/lib/List' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/lib/main' {
  declare module.exports: any;
}

declare module 'cycle-onionify/examples/mixed/lib/TodoApp' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/Collection' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/CollectionSource' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/index' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/onionify' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/pickCombine' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/pickMerge' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/StateSource' {
  declare module.exports: any;
}

declare module 'cycle-onionify/lib/types' {
  declare module.exports: any;
}

declare module 'cycle-onionify/test-with-rxjs' {
  declare module.exports: any;
}

declare module 'cycle-onionify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cycle-onionify/examples/advanced/dist/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/advanced/dist/main'>;
}
declare module 'cycle-onionify/examples/advanced/lib/Item.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/advanced/lib/Item'>;
}
declare module 'cycle-onionify/examples/advanced/lib/List.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/advanced/lib/List'>;
}
declare module 'cycle-onionify/examples/advanced/lib/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/advanced/lib/main'>;
}
declare module 'cycle-onionify/examples/advanced/lib/TodoApp.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/advanced/lib/TodoApp'>;
}
declare module 'cycle-onionify/examples/basic/dist/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/basic/dist/main'>;
}
declare module 'cycle-onionify/examples/basic/src/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/basic/src/main'>;
}
declare module 'cycle-onionify/examples/lenses/dist/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/dist/main'>;
}
declare module 'cycle-onionify/examples/lenses/lib/Edit.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/lib/Edit'>;
}
declare module 'cycle-onionify/examples/lenses/lib/Item.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/lib/Item'>;
}
declare module 'cycle-onionify/examples/lenses/lib/List.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/lib/List'>;
}
declare module 'cycle-onionify/examples/lenses/lib/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/lib/main'>;
}
declare module 'cycle-onionify/examples/lenses/lib/RadioApp.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/lenses/lib/RadioApp'>;
}
declare module 'cycle-onionify/examples/mixed/dist/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/dist/main'>;
}
declare module 'cycle-onionify/examples/mixed/lib/Counter.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/lib/Counter'>;
}
declare module 'cycle-onionify/examples/mixed/lib/Item.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/lib/Item'>;
}
declare module 'cycle-onionify/examples/mixed/lib/List.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/lib/List'>;
}
declare module 'cycle-onionify/examples/mixed/lib/main.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/lib/main'>;
}
declare module 'cycle-onionify/examples/mixed/lib/TodoApp.js' {
  declare module.exports: $Exports<'cycle-onionify/examples/mixed/lib/TodoApp'>;
}
declare module 'cycle-onionify/lib/Collection.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/Collection'>;
}
declare module 'cycle-onionify/lib/CollectionSource.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/CollectionSource'>;
}
declare module 'cycle-onionify/lib/index.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/index'>;
}
declare module 'cycle-onionify/lib/onionify.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/onionify'>;
}
declare module 'cycle-onionify/lib/pickCombine.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/pickCombine'>;
}
declare module 'cycle-onionify/lib/pickMerge.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/pickMerge'>;
}
declare module 'cycle-onionify/lib/StateSource.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/StateSource'>;
}
declare module 'cycle-onionify/lib/types.js' {
  declare module.exports: $Exports<'cycle-onionify/lib/types'>;
}
declare module 'cycle-onionify/test-with-rxjs.js' {
  declare module.exports: $Exports<'cycle-onionify/test-with-rxjs'>;
}
declare module 'cycle-onionify/test.js' {
  declare module.exports: $Exports<'cycle-onionify/test'>;
}
