// flow-typed signature: 0ac6604b039e5b8dee1f25892d7df53e
// flow-typed version: <<STUB>>/cycle-gun_v0.1.6/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cycle-gun'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cycle-gun' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cycle-gun/example/browser/bundle' {
  declare module.exports: any;
}

declare module 'cycle-gun/example/server/server' {
  declare module.exports: any;
}

declare module 'cycle-gun/lib/cycle-gun' {
  declare module.exports: any;
}

declare module 'cycle-gun/lib/index' {
  declare module.exports: any;
}

declare module 'cycle-gun/test/browser/bundle' {
  declare module.exports: any;
}

declare module 'cycle-gun/test/browser/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cycle-gun/example/browser/bundle.js' {
  declare module.exports: $Exports<'cycle-gun/example/browser/bundle'>;
}
declare module 'cycle-gun/example/server/server.js' {
  declare module.exports: $Exports<'cycle-gun/example/server/server'>;
}
declare module 'cycle-gun/lib/cycle-gun.js' {
  declare module.exports: $Exports<'cycle-gun/lib/cycle-gun'>;
}
declare module 'cycle-gun/lib/index.js' {
  declare module.exports: $Exports<'cycle-gun/lib/index'>;
}
declare module 'cycle-gun/test/browser/bundle.js' {
  declare module.exports: $Exports<'cycle-gun/test/browser/bundle'>;
}
declare module 'cycle-gun/test/browser/index.js' {
  declare module.exports: $Exports<'cycle-gun/test/browser/index'>;
}
