// flow-typed signature: 3e1949d481260ddad47355d90b6de2c4
// flow-typed version: <<STUB>>/serviceworker-webpack-plugin_v0.2.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serviceworker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serviceworker-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serviceworker-webpack-plugin/lib/browser/applyUpdate' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/browser/registerEvents' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/index.spec' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/runtime' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/runtimeLoader' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/lib/runtimeTemplate' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/browser/applyUpdate' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/browser/registerEvents' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/index.spec' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/runtime' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/runtimeLoader' {
  declare module.exports: any;
}

declare module 'serviceworker-webpack-plugin/src/runtimeTemplate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serviceworker-webpack-plugin/lib/browser/applyUpdate.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/browser/applyUpdate'>;
}
declare module 'serviceworker-webpack-plugin/lib/browser/registerEvents.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/browser/registerEvents'>;
}
declare module 'serviceworker-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/index'>;
}
declare module 'serviceworker-webpack-plugin/lib/index.spec.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/index.spec'>;
}
declare module 'serviceworker-webpack-plugin/lib/runtime.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/runtime'>;
}
declare module 'serviceworker-webpack-plugin/lib/runtimeLoader.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/runtimeLoader'>;
}
declare module 'serviceworker-webpack-plugin/lib/runtimeTemplate.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/lib/runtimeTemplate'>;
}
declare module 'serviceworker-webpack-plugin/src/browser/applyUpdate.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/browser/applyUpdate'>;
}
declare module 'serviceworker-webpack-plugin/src/browser/registerEvents.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/browser/registerEvents'>;
}
declare module 'serviceworker-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/index'>;
}
declare module 'serviceworker-webpack-plugin/src/index.spec.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/index.spec'>;
}
declare module 'serviceworker-webpack-plugin/src/runtime.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/runtime'>;
}
declare module 'serviceworker-webpack-plugin/src/runtimeLoader.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/runtimeLoader'>;
}
declare module 'serviceworker-webpack-plugin/src/runtimeTemplate.js' {
  declare module.exports: $Exports<'serviceworker-webpack-plugin/src/runtimeTemplate'>;
}
