// flow-typed signature: 79edfcd614e592b93a9d12dc814f62ec
// flow-typed version: <<STUB>>/union-type_v0.4.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'union-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'union-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'union-type/dist/union-type' {
  declare module.exports: any;
}

declare module 'union-type/example/build' {
  declare module.exports: any;
}

declare module 'union-type/example/example' {
  declare module.exports: any;
}

declare module 'union-type/test/index' {
  declare module.exports: any;
}

declare module 'union-type/union-type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'union-type/dist/union-type.js' {
  declare module.exports: $Exports<'union-type/dist/union-type'>;
}
declare module 'union-type/example/build.js' {
  declare module.exports: $Exports<'union-type/example/build'>;
}
declare module 'union-type/example/example.js' {
  declare module.exports: $Exports<'union-type/example/example'>;
}
declare module 'union-type/test/index.js' {
  declare module.exports: $Exports<'union-type/test/index'>;
}
declare module 'union-type/union-type.js' {
  declare module.exports: $Exports<'union-type/union-type'>;
}
