// flow-typed signature: 7eaf7e3fd825ea53054b191fb2e81112
// flow-typed version: <<STUB>>/webcomponentsjs_v^1.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webcomponentsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webcomponentsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webcomponentsjs/full' {
  declare module.exports: any;
}

declare module 'webcomponentsjs/lite' {
  declare module.exports: any;
}

declare module 'webcomponentsjs/micro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webcomponentsjs/full.js' {
  declare module.exports: $Exports<'webcomponentsjs/full'>;
}
declare module 'webcomponentsjs/lite.js' {
  declare module.exports: $Exports<'webcomponentsjs/lite'>;
}
declare module 'webcomponentsjs/micro.js' {
  declare module.exports: $Exports<'webcomponentsjs/micro'>;
}
