// flow-typed signature: 95fe05d40292e249e78844809fa304eb
// flow-typed version: <<STUB>>/xstream_v10.9.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xstream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xstream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xstream/dist/xstream' {
  declare module.exports: any;
}

declare module 'xstream/dist/xstream.min' {
  declare module.exports: any;
}

declare module 'xstream/extra/buffer' {
  declare module.exports: any;
}

declare module 'xstream/extra/concat' {
  declare module.exports: any;
}

declare module 'xstream/extra/debounce' {
  declare module.exports: any;
}

declare module 'xstream/extra/delay' {
  declare module.exports: any;
}

declare module 'xstream/extra/dropRepeats' {
  declare module.exports: any;
}

declare module 'xstream/extra/dropUntil' {
  declare module.exports: any;
}

declare module 'xstream/extra/flattenConcurrently' {
  declare module.exports: any;
}

declare module 'xstream/extra/flattenSequentially' {
  declare module.exports: any;
}

declare module 'xstream/extra/fromDiagram' {
  declare module.exports: any;
}

declare module 'xstream/extra/fromEvent' {
  declare module.exports: any;
}

declare module 'xstream/extra/pairwise' {
  declare module.exports: any;
}

declare module 'xstream/extra/sampleCombine' {
  declare module.exports: any;
}

declare module 'xstream/extra/split' {
  declare module.exports: any;
}

declare module 'xstream/extra/throttle' {
  declare module.exports: any;
}

declare module 'xstream/extra/tween' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xstream/dist/xstream.js' {
  declare module.exports: $Exports<'xstream/dist/xstream'>;
}
declare module 'xstream/dist/xstream.min.js' {
  declare module.exports: $Exports<'xstream/dist/xstream.min'>;
}
declare module 'xstream/extra/buffer.js' {
  declare module.exports: $Exports<'xstream/extra/buffer'>;
}
declare module 'xstream/extra/concat.js' {
  declare module.exports: $Exports<'xstream/extra/concat'>;
}
declare module 'xstream/extra/debounce.js' {
  declare module.exports: $Exports<'xstream/extra/debounce'>;
}
declare module 'xstream/extra/delay.js' {
  declare module.exports: $Exports<'xstream/extra/delay'>;
}
declare module 'xstream/extra/dropRepeats.js' {
  declare module.exports: $Exports<'xstream/extra/dropRepeats'>;
}
declare module 'xstream/extra/dropUntil.js' {
  declare module.exports: $Exports<'xstream/extra/dropUntil'>;
}
declare module 'xstream/extra/flattenConcurrently.js' {
  declare module.exports: $Exports<'xstream/extra/flattenConcurrently'>;
}
declare module 'xstream/extra/flattenSequentially.js' {
  declare module.exports: $Exports<'xstream/extra/flattenSequentially'>;
}
declare module 'xstream/extra/fromDiagram.js' {
  declare module.exports: $Exports<'xstream/extra/fromDiagram'>;
}
declare module 'xstream/extra/fromEvent.js' {
  declare module.exports: $Exports<'xstream/extra/fromEvent'>;
}
declare module 'xstream/extra/pairwise.js' {
  declare module.exports: $Exports<'xstream/extra/pairwise'>;
}
declare module 'xstream/extra/sampleCombine.js' {
  declare module.exports: $Exports<'xstream/extra/sampleCombine'>;
}
declare module 'xstream/extra/split.js' {
  declare module.exports: $Exports<'xstream/extra/split'>;
}
declare module 'xstream/extra/throttle.js' {
  declare module.exports: $Exports<'xstream/extra/throttle'>;
}
declare module 'xstream/extra/tween.js' {
  declare module.exports: $Exports<'xstream/extra/tween'>;
}
declare module 'xstream/index' {
  declare module.exports: $Exports<'xstream'>;
}
declare module 'xstream/index.js' {
  declare module.exports: $Exports<'xstream'>;
}
