// flow-typed signature: 675a763bce54f531811e75639291033d
// flow-typed version: <<STUB>>/@cycle/dom_v18.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/dom/dist/cycle-dom' {
  declare module.exports: any;
}

declare module '@cycle/dom/dist/cycle-dom.min' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/BodyDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/DocumentDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/DOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/ElementFinder' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/BodyDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/DocumentDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/DOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/ElementFinder' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/EventDelegator' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/fromEvent' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/hyperscript-helpers' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/index' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/isolate' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/IsolateModule' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/MainDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/makeDOMDriver' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/matchesSelector' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/mockDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/modules' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/ScopeChecker' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/thunk' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/utils' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/es6/VNodeWrapper' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/EventDelegator' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/fromEvent' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/hyperscript-helpers' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/index' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/isolate' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/IsolateModule' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/MainDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/makeDOMDriver' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/matchesSelector' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/mockDOMSource' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/modules' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/ScopeChecker' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/thunk' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/utils' {
  declare module.exports: any;
}

declare module '@cycle/dom/lib/VNodeWrapper' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/dom-driver' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/events' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/index' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/isolation' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/render' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/lib/select' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/browser/perf/index' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/manual-tests/advanced-list/src/app' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/manual-tests/advanced-list/src/main' {
  declare module.exports: any;
}

declare module '@cycle/dom/test/manual-tests/advanced-list/src/ticker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/dom/dist/cycle-dom.js' {
  declare module.exports: $Exports<'@cycle/dom/dist/cycle-dom'>;
}
declare module '@cycle/dom/dist/cycle-dom.min.js' {
  declare module.exports: $Exports<'@cycle/dom/dist/cycle-dom.min'>;
}
declare module '@cycle/dom/lib/BodyDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/BodyDOMSource'>;
}
declare module '@cycle/dom/lib/DocumentDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/DocumentDOMSource'>;
}
declare module '@cycle/dom/lib/DOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/DOMSource'>;
}
declare module '@cycle/dom/lib/ElementFinder.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/ElementFinder'>;
}
declare module '@cycle/dom/lib/es6/BodyDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/BodyDOMSource'>;
}
declare module '@cycle/dom/lib/es6/DocumentDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/DocumentDOMSource'>;
}
declare module '@cycle/dom/lib/es6/DOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/DOMSource'>;
}
declare module '@cycle/dom/lib/es6/ElementFinder.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/ElementFinder'>;
}
declare module '@cycle/dom/lib/es6/EventDelegator.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/EventDelegator'>;
}
declare module '@cycle/dom/lib/es6/fromEvent.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/fromEvent'>;
}
declare module '@cycle/dom/lib/es6/hyperscript-helpers.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/hyperscript-helpers'>;
}
declare module '@cycle/dom/lib/es6/index.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/index'>;
}
declare module '@cycle/dom/lib/es6/isolate.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/isolate'>;
}
declare module '@cycle/dom/lib/es6/IsolateModule.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/IsolateModule'>;
}
declare module '@cycle/dom/lib/es6/MainDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/MainDOMSource'>;
}
declare module '@cycle/dom/lib/es6/makeDOMDriver.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/makeDOMDriver'>;
}
declare module '@cycle/dom/lib/es6/matchesSelector.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/matchesSelector'>;
}
declare module '@cycle/dom/lib/es6/mockDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/mockDOMSource'>;
}
declare module '@cycle/dom/lib/es6/modules.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/modules'>;
}
declare module '@cycle/dom/lib/es6/ScopeChecker.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/ScopeChecker'>;
}
declare module '@cycle/dom/lib/es6/thunk.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/thunk'>;
}
declare module '@cycle/dom/lib/es6/utils.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/utils'>;
}
declare module '@cycle/dom/lib/es6/VNodeWrapper.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/es6/VNodeWrapper'>;
}
declare module '@cycle/dom/lib/EventDelegator.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/EventDelegator'>;
}
declare module '@cycle/dom/lib/fromEvent.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/fromEvent'>;
}
declare module '@cycle/dom/lib/hyperscript-helpers.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/hyperscript-helpers'>;
}
declare module '@cycle/dom/lib/index.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/index'>;
}
declare module '@cycle/dom/lib/isolate.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/isolate'>;
}
declare module '@cycle/dom/lib/IsolateModule.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/IsolateModule'>;
}
declare module '@cycle/dom/lib/MainDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/MainDOMSource'>;
}
declare module '@cycle/dom/lib/makeDOMDriver.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/makeDOMDriver'>;
}
declare module '@cycle/dom/lib/matchesSelector.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/matchesSelector'>;
}
declare module '@cycle/dom/lib/mockDOMSource.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/mockDOMSource'>;
}
declare module '@cycle/dom/lib/modules.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/modules'>;
}
declare module '@cycle/dom/lib/ScopeChecker.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/ScopeChecker'>;
}
declare module '@cycle/dom/lib/thunk.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/thunk'>;
}
declare module '@cycle/dom/lib/utils.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/utils'>;
}
declare module '@cycle/dom/lib/VNodeWrapper.js' {
  declare module.exports: $Exports<'@cycle/dom/lib/VNodeWrapper'>;
}
declare module '@cycle/dom/test/browser/lib/dom-driver.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/dom-driver'>;
}
declare module '@cycle/dom/test/browser/lib/events.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/events'>;
}
declare module '@cycle/dom/test/browser/lib/index.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/index'>;
}
declare module '@cycle/dom/test/browser/lib/isolation.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/isolation'>;
}
declare module '@cycle/dom/test/browser/lib/render.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/render'>;
}
declare module '@cycle/dom/test/browser/lib/select.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/lib/select'>;
}
declare module '@cycle/dom/test/browser/perf/index.js' {
  declare module.exports: $Exports<'@cycle/dom/test/browser/perf/index'>;
}
declare module '@cycle/dom/test/manual-tests/advanced-list/src/app.js' {
  declare module.exports: $Exports<'@cycle/dom/test/manual-tests/advanced-list/src/app'>;
}
declare module '@cycle/dom/test/manual-tests/advanced-list/src/main.js' {
  declare module.exports: $Exports<'@cycle/dom/test/manual-tests/advanced-list/src/main'>;
}
declare module '@cycle/dom/test/manual-tests/advanced-list/src/ticker.js' {
  declare module.exports: $Exports<'@cycle/dom/test/manual-tests/advanced-list/src/ticker'>;
}
