// flow-typed signature: b58256fa4e4972b9acb9fe7bcc5fe61f
// flow-typed version: <<STUB>>/@cycle/run_v3.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/run/dist/cycle-run' {
  declare module.exports: any;
}

declare module '@cycle/run/dist/cycle-run.min' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/adapt' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/es6/adapt' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/es6/index' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/es6/types' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/index' {
  declare module.exports: any;
}

declare module '@cycle/run/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/run/dist/cycle-run.js' {
  declare module.exports: $Exports<'@cycle/run/dist/cycle-run'>;
}
declare module '@cycle/run/dist/cycle-run.min.js' {
  declare module.exports: $Exports<'@cycle/run/dist/cycle-run.min'>;
}
declare module '@cycle/run/lib/adapt.js' {
  declare module.exports: $Exports<'@cycle/run/lib/adapt'>;
}
declare module '@cycle/run/lib/es6/adapt.js' {
  declare module.exports: $Exports<'@cycle/run/lib/es6/adapt'>;
}
declare module '@cycle/run/lib/es6/index.js' {
  declare module.exports: $Exports<'@cycle/run/lib/es6/index'>;
}
declare module '@cycle/run/lib/es6/types.js' {
  declare module.exports: $Exports<'@cycle/run/lib/es6/types'>;
}
declare module '@cycle/run/lib/index.js' {
  declare module.exports: $Exports<'@cycle/run/lib/index'>;
}
declare module '@cycle/run/lib/types.js' {
  declare module.exports: $Exports<'@cycle/run/lib/types'>;
}
