name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for build
        run: yarn install
      - name: Run tests
        run: yarn run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies for build
        run: yarn install
      - name: Make production build
        run: |
          yarn run build:ci
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.codetitlan.org
          username: ci-web-deployments@codetitlan.org
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: public_html/
